coverage:
  ignore:
    # ignore anything with the `mock_` pattern so we can use mocks across packages
    - '**/mock_*.go'
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%
