---
package:
  name: uds-security-hub-store
  version: 0.1.0
  description: UDS Security hub store
  target-architecture:
    - x86_64
    - amd64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - trivy
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - busybox
      - go
pipeline:
  - name: Build Go application
    runs: >
      set -x

      CGO_ENABLED=1 go build -o "${{targets.destdir}}/usr/sbin/store" ./cmd/store
  - name: Create dummy Docker config for Google Cloud
    runs: >
      set -x

      mkdir -p "${{targets.destdir}}/etc/store/docker-dummy"

      echo '{}' > "${{targets.destdir}}/etc/store/docker-dummy/config.json"
