name: Build and Push Melange and Apko

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      TAG_MODE: git

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3
        with:
          # there is a bug with the fetch-tags that requires that we have fetch-depth: 0
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v2

      - name: Cache Docker layers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GHCR
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # Use PAT with write:packages permission

      - name: Run build script
        run: ./scripts/build-apko-images.sh

      - name: Push Docker images
        run: |
          docker push ghcr.io/defenseunicorns/uds-security-hub:latest
          docker push ghcr.io/defenseunicorns/uds-security-hub-store:latest
          if [[ "${TAG_MODE:-}" == "git" ]]; then
            docker push ghcr.io/defenseunicorns/uds-security-hub:${GIT_TAG}
            docker push ghcr.io/defenseunicorns/uds-security-hub-store:${GIT_TAG}
          fi
        env:
          GIT_TAG: ${{ github.ref_name }}
