name: Build and Push Melange and Apko

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v2

      - name: Cache Docker layers
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GHCR
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} # Use PAT with write:packages permission

      - name: Set TAG_MODE
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_MODE=git" >> $GITHUB_ENV

      - name: Run build script
        run: ./scripts/build.sh

      - name: Push Docker images
        run: |
          docker push ghcr.io/defenseunicorns/uds-security-hub:latest
          if [[ "${TAG_MODE:-}" == "git" ]]; then
            docker push ghcr.io/defenseunicorns/uds-security-hub:${GIT_TAG}
          fi
        env:
          GIT_TAG: ${{ github.ref_name }}