name: Test Goreleaser Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-goreleaser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        fetch-depth: 0
        ref: ${{ inputs.commit }}

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.22.4'
        check-latest: true

    - name: Create temporary Git tag
      run: |
        git tag v0.0.0-temp-tag

    - name: Run GoReleaser
      id: run-goreleaser
      uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete temporary Git tag
      run: |
        git tag -d v0.0.0-temp-tag
