name: Test Goreleaser Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-goreleaser:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 0
        ref: ${{ inputs.commit }}

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: '1.22.4'
        check-latest: true

    - name: Create temporary Git tag
      run: |
        git tag v0.0.0-temp-tag

    - name: Run GoReleaser
      id: run-goreleaser
      uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
      with:
        version: latest
        args: release --skip publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete temporary Git tag
      run: |
        git tag -d v0.0.0-temp-tag
