name: Leapfrog Scan

on:
  schedule:
    - cron: '0 23 * * *'  
  workflow_dispatch:      

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read  


    steps:
      - name: Checkout repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: '1.22.4'  

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Leapfrog Scan
        env:
          GHCR_CREDS: ${{ secrets.GHCR_CREDS }}
          REGISTRY1_CREDS: ${{ secrets.REGISTRY1_CREDS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_IO_CREDS: ${{ secrets.DOCKER_IO_CREDS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
        run: |
          chmod +x scripts/scan.sh
          ./scripts/scan.sh -f leapfrog_names.txt -v 1
