name: SLSA Builds

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: write
      actions: read
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
        with:
          go-version: 1.22
          config-file: .slsa-goreleaser/${{ matrix.os }}-${{ matrix.arch }}.yml
